// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxC7GCy8GBa5PcajsuzxqFEpLFjMZl8Pk',
    appId: '1:376290603534:web:6dda56a43d9e7f1e1a025f',
    messagingSenderId: '376290603534',
    projectId: 'cjdsusehrflqakstp',
    authDomain: 'cjdsusehrflqakstp.firebaseapp.com',
    storageBucket: 'cjdsusehrflqakstp.appspot.com',
    measurementId: 'G-P4HJYGMLP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7eGmo22dz3qZ_32YekGrGgQ2REqyhg_A',
    appId: '1:376290603534:android:a76e30bbd847baf81a025f',
    messagingSenderId: '376290603534',
    projectId: 'cjdsusehrflqakstp',
    storageBucket: 'cjdsusehrflqakstp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYwjhc_2N0Bu5dTYT_B-HAMXYLR6_YGQ',
    appId: '1:376290603534:ios:06e5184818ee93171a025f',
    messagingSenderId: '376290603534',
    projectId: 'cjdsusehrflqakstp',
    storageBucket: 'cjdsusehrflqakstp.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYwjhc_2N0Bu5dTYT_B-HAMXYLR6_YGQ',
    appId: '1:376290603534:ios:a95d97d33936dba31a025f',
    messagingSenderId: '376290603534',
    projectId: 'cjdsusehrflqakstp',
    storageBucket: 'cjdsusehrflqakstp.appspot.com',
    iosBundleId: 'com.example.sample.RunnerTests',
  );
}
